# Generated by Django 2.2.6 on 2019-10-15 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('mobile', models.IntegerField(max_length=10, verbose_name='mob')),
                ('userrname', models.CharField(max_length=250, verbose_name='user')),
                ('age', models.IntegerField(verbose_name='age')),
                ('city', models.CharField(max_length=10, verbose_name='city')),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('mobile', models.IntegerField(max_length=10, verbose_name='mob')),
                ('date', models.DateField(verbose_name='date')),
                ('dis', models.CharField(max_length=250, verbose_name='dis')),
                ('med', models.CharField(max_length=2000, verbose_name='med')),
                ('username', models.CharField(max_length=250, verbose_name='username')),
                ('pid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proj.patient')),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250, verbose_name='email')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('age', models.IntegerField(default=0, verbose_name='age')),
                ('mobile', models.CharField(max_length=10, verbose_name='mobile')),
                ('reg', models.CharField(max_length=250, verbose_name='reg')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
